<?php
$siteName = 'CineRez';
$ticketPrices = [
    'adult' => 5.00,
    'student' => 3.50,
    'child' => 2.50,
];

$cinemaLocations = ['Prishtina', 'Prizren', 'Peja', 'Gjilan'];

$movies = [
    [
        'id' => 1,
        'title' => 'The Super Mario Galaxy Movie',
        'genre' => 'Animation',
        'duration' => 98,
        'rating' => 7.1,
        'age_rating' => 'PG',
        'description' => 'Mario, Luigi, and friends head into space to stop Bowser and Bowser Jr. from unleashing chaos across the galaxy.',
        'poster' => 'movie1.jpg',
        'price' => 6.00,
        'featured' => true,
        'showtimes' => ['16:00', '18:30', '21:00'],
        'director' => 'Aaron Horvath, Michael Jelenic',
        'release_date' => '2026-04-01',
        'cast' => ['Chris Pratt', 'Anya Taylor-Joy', 'Jack Black'],
    ],
    [
        'id' => 2,
        'title' => 'Project Hail Mary',
        'genre' => 'Sci-Fi',
        'duration' => 156,
        'rating' => 8.0,
        'age_rating' => 'PG-13',
        'description' => 'An astronaut awakens alone on a mission to save Earth and forms an unlikely interstellar alliance.',
        'poster' => 'movie2.jpg',
        'price' => 6.00,
        'featured' => true,
        'showtimes' => ['15:30', '19:00', '22:00'],
        'director' => 'Phil Lord, Christopher Miller',
        'release_date' => '2026-03-20',
        'cast' => ['Ryan Gosling', 'Sandra Huller', 'James Ortiz'],
    ],
    [
        'id' => 3,
        'title' => 'Lee Cronin\'s The Mummy',
        'genre' => 'Horror',
        'duration' => 134,
        'rating' => 6.3,
        'age_rating' => 'R',
        'description' => 'A family is reunited with their long-missing daughter, only to discover the return carries a terrifying curse.',
        'poster' => 'movie3.jpg',
        'price' => 5.50,
        'featured' => false,
        'showtimes' => ['14:00', '17:00', '20:30'],
        'director' => 'Lee Cronin',
        'release_date' => '2026-04-17',
        'cast' => ['Jack Reynor', 'Laia Costa', 'Natalie Grace'],
    ],
    [
        'id' => 4,
        'title' => 'The Drama',
        'genre' => 'Drama',
        'duration' => 105,
        'rating' => 6.8,
        'age_rating' => 'R',
        'description' => 'An engaged couple\'s final week before their wedding unravels after an unexpected revelation.',
        'poster' => 'movie4.jpg',
        'price' => 5.50,
        'featured' => false,
        'showtimes' => ['18:00', '20:00', '22:30'],
        'director' => 'Kristoffer Borgli',
        'release_date' => '2026-04-03',
        'cast' => ['Zendaya', 'Robert Pattinson', 'Alana Haim'],
    ],
    [
        'id' => 5,
        'title' => 'You, Me & Tuscany',
        'genre' => 'Romance',
        'duration' => 105,
        'rating' => 6.4,
        'age_rating' => 'PG-13',
        'description' => 'A young chef travels to Tuscany and gets pulled into a fake engagement that turns real.',
        'poster' => 'movie5.jpg',
        'price' => 4.00,
        'featured' => false,
        'showtimes' => ['13:00', '16:30', '19:30'],
        'director' => 'Kat Coiro',
        'release_date' => '2026-04-10',
        'cast' => ['Halle Bailey', 'Rege-Jean Page', 'Marco Calvani'],
    ],
    [
        'id' => 6,
        'title' => 'Hoppers',
        'genre' => 'Animation',
        'duration' => 104,
        'rating' => 7.3,
        'age_rating' => 'PG',
        'description' => 'A college student uses mind-transfer tech to communicate with animals and protect their habitat.',
        'poster' => 'movie6.jpg',
        'price' => 6.50,
        'featured' => true,
        'showtimes' => ['15:00', '18:00', '21:30'],
        'director' => 'Daniel Chong',
        'release_date' => '2026-03-06',
        'cast' => ['Piper Curda', 'Bobby Moynihan', 'Jon Hamm'],
    ],
    [
        'id' => 7,
        'title' => 'Reminders of Him',
        'genre' => 'Drama',
        'duration' => 114,
        'rating' => 6.6,
        'age_rating' => 'PG-13',
        'description' => 'A woman returning from prison seeks redemption and a second chance with her daughter.',
        'poster' => 'movie7.jpg',
        'price' => 5.00,
        'featured' => false,
        'showtimes' => ['14:30', '17:45', '20:45'],
        'director' => 'Vanessa Caswill',
        'release_date' => '2026-03-13',
        'cast' => ['Maika Monroe', 'Tyriq Withers', 'Rudy Pankow'],
    ],
    [
        'id' => 8,
        'title' => 'A Great Awakening',
        'genre' => 'Drama',
        'duration' => 129,
        'rating' => 7.0,
        'age_rating' => 'PG-13',
        'description' => 'The friendship between George Whitefield and Benjamin Franklin shapes a pivotal chapter in American history.',
        'poster' => 'movie8.jpg',
        'price' => 4.50,
        'featured' => false,
        'showtimes' => ['13:30', '16:00', '19:00'],
        'director' => 'Joshua Enck',
        'release_date' => '2026-04-03',
        'cast' => ['Jonathan Blair', 'John Paul Sneed', 'Josh Bates'],
    ],
];

$users = [
    [
        'name' => 'Demo User',
        'email' => 'user@cinerez.com',
        'password' => 'User123',
        'role' => 'user',
    ],
    [
        'name' => 'Cinema Admin',
        'email' => 'admin@cinerez.com',
        'password' => 'Admin123',
        'role' => 'admin',
    ],
];

$dummyReservations = [
    ['code' => 'CRZ-2026-1201', 'customer' => 'Arta H.', 'movie_id' => 2, 'seats' => ['B2', 'B3'], 'total' => 12.00],
    ['code' => 'CRZ-2026-1202', 'customer' => 'Erion P.', 'movie_id' => 6, 'seats' => ['D4', 'D5', 'D6'], 'total' => 16.50],
    ['code' => 'CRZ-2026-1203', 'customer' => 'Lena K.', 'movie_id' => 1, 'seats' => ['F7'], 'total' => 5.00],
    ['code' => 'CRZ-2026-1204', 'customer' => 'Besa M.', 'movie_id' => 8, 'seats' => ['C1', 'C2'], 'total' => 9.00],
];

$occupiedSeats = ['A3', 'A4', 'B5', 'C2', 'C8', 'D6', 'E1', 'F9', 'G4', 'H7'];
